import re
from datetime import datetime

def parse_generated_report(raw_report_text: str) -> tuple[str, str]:
    """
    Parses the raw output from ChestXRayReportGeneratorTool to extract
    Findings and Impression sections.

    Args:
        raw_report_text: The raw report string from the generator.

    Returns:
        A tuple containing (findings_text, impression_text).
        Returns (None, None) if parsing fails.
    """
    findings_match = re.search(r"FINDINGS:\n(.*?)\n\nIMPRESSION:", raw_report_text, re.DOTALL)
    impression_match = re.search(r"IMPRESSION:\n(.*)", raw_report_text, re.DOTALL)

    findings_text = findings_match.group(1).strip() if findings_match else "Not available"
    impression_text = impression_match.group(1).strip() if impression_match else "Not available"

    # Handle cases where the generator might output empty strings or placeholders
    if not findings_text:
        findings_text = "No specific findings reported by the generator."
    if not impression_text:
        impression_text = "No specific impression reported by thegenerator."

    return findings_text, impression_text

def create_doctor_preliminary_report(
    raw_report_text: str,
    image_identifier: str,
    report_generator_tool_name: str = "ChestXRayReportGeneratorTool"
) -> str:
    """
    Generates a structured preliminary report for doctors based on the
    raw output of an X-ray report generation tool.

    Args:
        raw_report_text: The raw report string from the generator.
        image_identifier: An identifier for the image (e.g., file path or patient ID).
        report_generator_tool_name: Name of the tool that generated the raw report.

    Returns:
        A string containing the structured preliminary report for doctors.
    """
    findings, impression = parse_generated_report(raw_report_text)
    analysis_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report_parts = [
        "**Doctor-Focused Preliminary CXR Report**",
        "-----------------------------------------",
        f"**Patient Information:**",
        f"  Identifier: {image_identifier}",
        f"  Date of Study (Analysis Time): {analysis_timestamp}",
        "",
        "**Clinical Indication:**",
        "  Not provided (This is an automated analysis).",
        "",
        "**Comparison:**",
        "  No prior studies automatically compared by this preliminary report.",
        "  Manual review for comparison with priors is recommended if available.",
        "",
        "**Technique:**",
        "  Automated analysis of digital chest X-ray using AI.",
        "",
        "**Findings:**",
        f"  {findings}",
        "",
        "**Impression:**",
        f"  {impression}",
        "",
        "**Source & Confidence:**",
        f"  Report generated by MedRAX AI agent, utilizing the {report_generator_tool_name}.",
        "  Confidence levels for specific findings are not explicitly provided by the current generator.",
        "",
        "**Disclaimer:**",
        "  This is an AI-generated preliminary report. It requires review and confirmation by a qualified",
        "  radiologist or physician. It is not a substitute for professional medical advice, diagnosis, or treatment.",
        "-----------------------------------------"
    ]

    return "\n".join(report_parts)

if __name__ == '__main__':
    # Example Usage for testing
    sample_raw_report_findings_impression = """CHEST X-RAY REPORT

FINDINGS:
The lungs are clear. The cardiomediastinal silhouette is normal. Pleural spaces are clear. Osseous structures are unremarkable.

IMPRESSION:
No acute cardiopulmonary process.
"""
    print("--- Example 1: Standard Report ---")
    report1 = create_doctor_preliminary_report(sample_raw_report_findings_impression, "test_image_001.jpg")
    print(report1)
    print("\\n--- Example 2: Report with Missing Impression ---")
    sample_raw_report_missing_impression = """CHEST X-RAY REPORT

FINDINGS:
Lungs demonstrate patchy opacities in the right lower lobe, suspicious for pneumonia.

IMPRESSION:
"""
    report2 = create_doctor_preliminary_report(sample_raw_report_missing_impression, "test_image_002.png")
    print(report2)

    print("\\n--- Example 3: Report with Minimal Findings ---")
    sample_raw_report_minimal_findings = """CHEST X-RAY REPORT

FINDINGS:

IMPRESSION:
Normal chest X-ray.
"""
    report3 = create_doctor_preliminary_report(sample_raw_report_minimal_findings, "test_image_003.dcm")
    print(report3)

    print("\\n--- Example 4: Malformed/Unexpected Report ---")
    sample_raw_report_malformed = """CHEST X-RAY FINDINGS: Some text here but not the expected format. IMPRESSION: Also some text."""
    report4 = create_doctor_preliminary_report(sample_raw_report_malformed, "test_image_004.jpeg")
    print(report4)


# --- Patient-Focused Report Generation Logic ---

def create_patient_simplification_prompt(findings_text: str, impression_text: str) -> str:
    """
    Creates a detailed prompt for an LLM to generate a simplified, patient-focused
    explanation of chest X-ray findings and impression.

    Args:
        findings_text: The medical findings text.
        impression_text: The medical impression text.

    Returns:
        A string containing the prompt to be sent to an LLM.
    """

    prompt = f"""You are a helpful medical assistant AI. Your task is to explain the results of a chest X-ray analysis to a patient in simple, clear, and reassuring language.

**STRICT INSTRUCTIONS:**
1.  **DO NOT PROVIDE A DIAGNOSIS.** Never say "you have X condition."
2.  **ALWAYS EMPHASIZE THE NEED TO CONSULT THEIR DOCTOR.** This is the most important part.
3.  Use layperson's terms. Avoid complex medical jargon. If a term is necessary, explain it very simply.
4.  Be calm and reassuring, especially if the findings are normal. If there are abnormalities, present them factually but gently, focusing on the doctor's role in interpretation.
5.  Structure your explanation according to the template provided below.
6.  The medical findings and impression provided are from an automated AI analysis of the X-ray and are preliminary.

**Medical Findings from Automated Analysis:**
"{findings_text}"

**Medical Impression from Automated Analysis:**
"{impression_text}"

**Patient Explanation Template:**

**Understanding Your Chest X-ray Examination**
*   Start with a brief, simple explanation of what a chest X-ray is (e.g., "This is an explanation of the automated analysis of your recent chest X-ray. A chest X-ray is a picture that helps doctors look at your lungs, heart, and bones in your chest.").

**What the Automated Analysis Observed**
*   Summarize the key findings and impression in simple terms.
*   Example (if normal): "The automated analysis suggests that your lungs appear clear and your heart size appears normal in this X-ray."
*   Example (if abnormal): "The automated analysis noted an area in your [e.g., right lung] that your doctor will look at more closely. This might suggest [e.g., some inflammation or an infection]."

**What These Observations Could Mean**
*   Provide very general, non-alarming context.
*   Example: "Observations like these can be due to various reasons. Your doctor will look at these findings along with your overall health and any symptoms you might have to understand them better."

**Very Important: Your Doctor's Role**
*   Strongly emphasize:
    *   "This automated explanation is **NOT a diagnosis**."
    *   "It is a tool to help your doctor, who has your full medical history and can provide a complete interpretation of your X-ray."
    *   "**Please discuss these results thoroughly with your doctor.** They will explain what these observations mean for your health and determine any next steps."

**About this Explanation**
*   "This explanation was generated by the MedRAX AI system based on an automated analysis of your X-ray. It is intended to help you prepare for your discussion with your doctor."

**Important Disclaimer**
*   "This information is for educational purposes only and should not be considered medical advice. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition."

---
Now, please generate the patient explanation based on the provided medical findings and impression, strictly following the template and all instructions.
"""
    return prompt

def generate_patient_focused_report_placeholder(findings_text: str, impression_text: str) -> str:
    """
    Generates a structured, simplified preliminary report for patients.
    This is a PLACEHOLDER function. In a real scenario, the prompt generated by
    `create_patient_simplification_prompt` would be sent to an LLM.
    This function simulates a simplified LLM response for common cases.

    Args:
        findings_text: The medical findings text.
        impression_text: The medical impression text.

    Returns:
        A string containing the structured simplified report for patients.
    """
    # Basic logic for placeholder - a real LLM would be more nuanced.
    simplified_observation = "The automated analysis looked at your X-ray."
    simplified_meaning = "Your doctor will discuss these observations with you."

    # Convert to lowercase for easier keyword spotting (very basic)
    findings_lower = findings_text.lower()
    impression_lower = impression_text.lower()

    if "clear" in findings_lower and ("normal" in impression_lower or "no acute" in impression_lower or "unremarkable" in impression_lower):
        simplified_observation = "The automated analysis suggests that your lungs appear clear and your heart size appears normal in this X-ray. No significant abnormalities were noted."
        simplified_meaning = "This is generally a good sign. Your doctor will confirm these findings and discuss them in the context of your overall health."
    elif "pneumonia" in findings_lower or "pneumonia" in impression_lower or "opacity" in findings_lower or "infiltrate" in findings_lower:
        simplified_observation = "The automated analysis noted some signs in your lungs (such as areas called opacities or infiltrates) that might suggest an infection or inflammation, like pneumonia. Your doctor will review this carefully."
        simplified_meaning = "Observations like these often mean your body is fighting an infection. Your doctor will look at these findings along with your symptoms to decide on the best course of action."
    elif "nodule" in findings_lower or "mass" in findings_lower or "nodule" in impression_lower or "mass" in impression_lower:
        simplified_observation = "The automated analysis noted a small spot (often called a nodule or mass) in your lungs. Your doctor will look at this very carefully."
        simplified_meaning = "Spots like these can be due to many reasons, and many are not serious. However, it's important that your doctor investigates it further, possibly with more tests or by comparing with any previous X-rays you might have had."
    elif "effusion" in findings_lower or "effusion" in impression_lower:
        simplified_observation = "The automated analysis suggests there might be some fluid in the space around your lungs (this is called a pleural effusion). Your doctor will examine this."
        simplified_meaning = "Fluid in this area can happen for various reasons. Your doctor will investigate to understand why it's there and what it means for you."
    else:
        simplified_observation = "The automated analysis of your X-ray showed some specific details about your lungs, heart, and chest structures. Your doctor will review these findings."
        simplified_meaning = "It's important to discuss these observations with your doctor, who can interpret them in the context of your overall health and any symptoms you may be experiencing."


    report_parts = [
        "**Understanding Your Chest X-ray Examination**",
        "This report provides a simple explanation of the automated analysis of your recent chest X-ray. A chest X-ray is a picture that helps doctors look at your lungs, heart, and bones in your chest.",
        "",
        "**What the Automated Analysis Observed**",
        simplified_observation,
        "",
        "**What These Observations Could Mean**",
        simplified_meaning,
        "",
        "**Very Important: Your Doctor's Role**",
        "This automated explanation is **NOT a diagnosis**.",
        "It is a tool to help your doctor, who has your full medical history and can provide a complete interpretation of your X-ray.",
        "**Please discuss these results thoroughly with your doctor.** They will explain what these observations mean for your health and determine any next steps.",
        "",
        "**About this Explanation**",
        "This explanation was generated by the MedRAX AI system based on an automated analysis of your X-ray. It is intended to help you prepare for your discussion with your doctor.",
        "",
        "**Important Disclaimer**",
        "This information is for educational purposes only and should not be considered medical advice. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.",
        "-----------------------------------------"
    ]
    return "\n".join(report_parts)


if __name__ == '__main__':
    # Example Usage for testing
    sample_raw_report_findings_impression = """CHEST X-RAY REPORT

FINDINGS:
The lungs are clear. The cardiomediastinal silhouette is normal. Pleural spaces are clear. Osseous structures are unremarkable.

IMPRESSION:
No acute cardiopulmonary process.
"""
    print("--- Example 1: Standard Report (Doctor) ---")
    doctor_report1 = create_doctor_preliminary_report(sample_raw_report_findings_impression, "test_image_001.jpg")
    print(doctor_report1)
    findings1, impression1 = parse_generated_report(sample_raw_report_findings_impression)
    print("\\n--- Example 1: Patient Simplification Prompt ---")
    # patient_prompt1 = create_patient_simplification_prompt(findings1, impression1)
    # print(patient_prompt1) # This would be sent to an LLM
    print("\\n--- Example 1: Patient Report (Placeholder) ---")
    patient_report1_placeholder = generate_patient_focused_report_placeholder(findings1, impression1)
    print(patient_report1_placeholder)


    print("\\n--- Example 2: Report with Missing Impression (Doctor) ---")
    sample_raw_report_missing_impression = """CHEST X-RAY REPORT

FINDINGS:
Lungs demonstrate patchy opacities in the right lower lobe, suspicious for pneumonia.

IMPRESSION:
"""
    doctor_report2 = create_doctor_preliminary_report(sample_raw_report_missing_impression, "test_image_002.png")
    print(doctor_report2)
    findings2, impression2 = parse_generated_report(sample_raw_report_missing_impression)
    # print("\\n--- Example 2: Patient Report (Placeholder) ---")
    # patient_prompt2 = create_patient_simplification_prompt(findings2, impression2)
    # print(patient_prompt2)
    print("\\n--- Example 2: Patient Report (Placeholder) ---")
    patient_report2_placeholder = generate_patient_focused_report_placeholder(findings2, impression2)
    print(patient_report2_placeholder)


    print("\\n--- Example 3: Report with Nodule (Doctor) ---")
    sample_raw_report_nodule = """CHEST X-RAY REPORT

FINDINGS:
A 1.5 cm spiculated nodule is seen in the left upper lobe. Otherwise, lungs are clear.

IMPRESSION:
Suspicious nodule in LUL, recommend CT chest for further evaluation.
"""
    doctor_report3 = create_doctor_preliminary_report(sample_raw_report_nodule, "test_image_003.dcm")
    print(doctor_report3)
    findings3, impression3 = parse_generated_report(sample_raw_report_nodule)
    # print("\\n--- Example 3: Patient Report (Placeholder) ---")
    # patient_prompt3 = create_patient_simplification_prompt(findings3, impression3)
    # print(patient_prompt3)
    print("\\n--- Example 3: Patient Report (Placeholder) ---")
    patient_report3_placeholder = generate_patient_focused_report_placeholder(findings3, impression3)
    print(patient_report3_placeholder)
